name: Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        name: test
        runs-on: ubuntu-latest
        env:
            PORT: ${{ secrets.PORT }}
            RC_AUTH_ID: ${{ secrets.RC_AUTH_ID }}
            RC_AUTH_SECRET: ${{ secrets.RC_AUTH_SECRET }}
            MONGO_URI: ${{ secrets.MONGO_URI }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
            - name: shell
              run: echo "${PORT}"
            - name: install packages
              run: yarn install
            - name: run tests
              run: yarn test
